x-app: &app
  build:
    args:
      USER_UID: "${UID:-1000}"
      USER_GID: "${GID:-100}"
  image: berlin-ai:latest
  user: dev
  tmpfs:
    - /tmp

x-backend: &backend
  <<: *app
  stdin_open: true
  tty: true
  volumes:
    - .:/app:cached
    - bundle:/usr/local/bundle
    - ~/.ssh/id_rsa:/home/dev/.ssh/id_rsa:ro
    - ~/.ssh/id_rsa.pub:/home/dev/.ssh/id_rsa.pub:ro
    - ~/.ssh/known_hosts:/home/dev/.ssh/known_hosts
  environment:
    HISTFILE: /app/log/.bash_history

services:
  runner:
    <<: *backend
    command: /bin/bash
    # Inline command in this service doesn't catch SIGTERM to stop so we have to send directly a SIGKILL
    stop_signal: SIGKILL
  sinatra:
    <<: *backend
    entrypoint: ./entrypoint.sh

volumes:
  bundle:
